# ===============================
# Run setup (NO VISUALIZATION)
# ===============================
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Multi-thread
/run/numberOfThreads 40


# Initialize
/run/initialize

# ===============================
# Source setup
# ===============================
/gps/particle ion
/gps/ion 55 137

/gps/pos/type Point
/gps/pos/centre 0 0 1.55 cm

/gps/ene/type Mono
/gps/ene/mono 662 eV


/process/had/rdm/thresholdForVeryLongDecayTime 1.0e+60 year


# ===============================
# RUN SIMULATION (WAJIB)
# ===============================
/run/beamOn 100000000
